version: "3"

tasks:
  build:
    cmds:
      - python3 setup.py build_ext --inplace
    sources:
      - "*.pyx"
      - "setup.py"
    generates:
      - "build/"
      - "*.c"
      - "*.so"

  run:
    cmds:
      - python3 -c "import bench"
    silent: true
